global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: cerera-node
    metrics_path: /metrics
    static_configs:
      # Сбор метрик с одной ноды через Docker network
      - targets:
          - "node1:1337"
        labels:
          cluster: "cerera"
          node: "node1"
