version: "3.8"

services:
  node1:
    build:
      context: ..
      dockerfile: ci-cd/Dockerfile
    container_name: cerera-node1
    command: ["cerera", "--mode=p2p", "--http=1337", "--port=31100", "--mem=true", "--miner"]
    ports:
      - "1337:1337"
      - "31100:31100"
    volumes:
      - node1_data:/app/data
      - node1_config:/app/config
    restart: unless-stopped
    networks:
      - cerera-network

  node2:
    build:
      context: ..
      dockerfile: ci-cd/Dockerfile
    container_name: cerera-node2
    command: ["cerera", "--mode=p2p", "--http=1338", "--port=31101", "--mem=true", "--miner"]
    ports:
      - "1338:1338"
      - "31101:31101"
    volumes:
      - node2_data:/app/data
      - node2_config:/app/config
    restart: unless-stopped
    networks:
      - cerera-network

  node3:
    build:
      context: ..
      dockerfile: ci-cd/Dockerfile
    container_name: cerera-node3
    command: ["cerera", "--mode=p2p", "--http=1339", "--port=31102", "--mem=true", "--miner"]
    ports:
      - "1339:1339"
      - "31102:31102"
    volumes:
      - node3_data:/app/data
      - node3_config:/app/config
    restart: unless-stopped
    networks:
      - cerera-network

  node4:
    build:
      context: ..
      dockerfile: ci-cd/Dockerfile
    container_name: cerera-node4
    command: ["cerera", "--mode=p2p", "--http=1340", "--port=31103", "--mem=true", "--miner"]
    ports:
      - "1340:1340"
      - "31103:31103"
    volumes:
      - node4_data:/app/data
      - node4_config:/app/config
    restart: unless-stopped
    networks:
      - cerera-network

  node5:
    build:
      context: ..
      dockerfile: ci-cd/Dockerfile
    container_name: cerera-node5
    command: ["cerera", "--mode=p2p", "--http=1341", "--port=31104", "--mem=true", "--miner"]
    ports:
      - "1341:1341"
      - "31104:31104"
    volumes:
      - node5_data:/app/data
      - node5_config:/app/config
    restart: unless-stopped
    networks:
      - cerera-network

volumes:
  node1_data:
  node1_config:
  node2_data:
  node2_config:
  node3_data:
  node3_config:
  node4_data:
  node4_config:
  node5_data:
  node5_config:

networks:
  cerera-network:
    driver: bridge

